### ISSUE TITLE
How configure on SqlServer

### ISSUE THREAD

**Issue by mtugnoli** [iamoldli/NetModular#8]
Great project !

How configure on SqlServer ?
Have a migration procedure ?
PS: it would be great if it had language management

**Comment by iamoldli** [comment]
In `src/WebHost/conifg/db.json` file，the `Dialect` property can configure database type，

0:SqlServer 1:MySql 2:SQLite

```
{
  "Logging": true,
  "Connections": [
    {
      "Name": "Admin",
      "Dialect": 0,
      "Database": "Nm_Admin",
      "ConnString": "Server=.;Database=Nm_Admin;Uid=sa;Pwd=sa;MultipleActiveResultSets=true;"
    },
```

**Comment by mtugnoli** [comment]
Thank you for your answer, but how create tables ?
I try to run on Visual Studio 2019 (in debug mode), but I see only a blank page
on http://localhost:5000/api/values

**Comment by iamoldli** [comment]
You should create the database first, the database file is in `data`  directory，for sqlserver：`data\SqlServer`

Because the project is Front-end and Back-end separation, so you have to start the  Front-end and back-end .

For Back-end, you can start the WebHost in visual studio， or open WebHost directory and powershell ,run `dotnet watch run`，then you can open [http://localhost:6220/swagger/index.html](http://localhost:6220/swagger/index.html) and see the api document.

For Front-end, you need had install node.js, then open WebUI directory and run the following command 

```
npm install
npm run serve
```

now, open [http://localhost:5220](http://localhost:5220)

My English is not very good, please forgive me~

**Comment by jianyang1982** [comment]
sql server 2008 r2 上面分页有兼容性问题，不支持 offset  ,需要使用row_number(),
  public override string GeneratePagingSql(string select, string table, string where, string sort, int skip, int take)
        {
            var sqlBuilder = new StringBuilder();
            /* 2012及以后支持offset写法，为适应2008，修改为rownumber()方法
             * sqlBuilder.AppendFormat("SELECT {0} FROM {1}", select, table);
             if (!string.IsNullOrWhiteSpace(where))
                 sqlBuilder.AppendFormat(" WHERE {0}", where);

             sqlBuilder.AppendFormat(" ORDER BY {0} OFFSET {1} ROW FETCH NEXT {2} ROW ONLY", sort, skip, take);
             
             */

            sqlBuilder.AppendFormat("SELECT * from ( select row_number() over ( order by  {0} ) as _tempId,* from  ( select  {1} FROM {2}    ", sort, select, table);
           if (!string.IsNullOrWhiteSpace(where))
                sqlBuilder.AppendFormat(" WHERE {0}", where);
            sqlBuilder.AppendFormat( "  ) as T1 ) as pageSqlOuter where _tempId >={0} and _tempId<={1} ",skip+1,skip+take); //默认内部分层重命名为T1 ,有的orderby会带上T1前缀(角色管理)，按道理都不应该带

            return sqlBuilder.ToString();

        }
